# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# Activate recommended lints for Flutter apps.
#include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Suppress warnings for unused imports
    unused_import: ignore
    # Suppress unused_element warnings in test files
    unused_element: ignore

linter:
  rules:
    # Style and Formatting
    - always_declare_return_types # Useful for clarity and avoiding implicit dynamic types.
    - annotate_overrides # Required for explicit overrides.

    # Performance and Optimization
    - prefer_const_literals_to_create_immutables # Use const for immutable data structures.

    # Readability and Maintainability
    - avoid_empty_else # Avoid having empty else blocks.
    - prefer_relative_imports # Encourage relative imports for project consistency.

 
# Optional: You can re-enable the full set of lint rules later by reverting to the full configuration.
