// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE83jbFQcMsuuqmcqhglqJcwD5SrvQUuc',
    appId: '1:201460195049:web:43fe6736d9fce5c48c1a78',
    messagingSenderId: '201460195049',
    projectId: 'recipe-app-39a72',
    authDomain: 'recipe-app-39a72.firebaseapp.com',
    storageBucket: 'recipe-app-39a72.firebasestorage.app',
    measurementId: 'G-8KX15PE4RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KmCsED_u8QnJWo3zEKulr-UEZr7AqdY',
    appId: '1:201460195049:android:899ca87a0ccdccb88c1a78',
    messagingSenderId: '201460195049',
    projectId: 'recipe-app-39a72',
    storageBucket: 'recipe-app-39a72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvztd0ASYHtelJc7P8FzZhcWgypH_hCOk',
    appId: '1:201460195049:ios:903263870401e0e28c1a78',
    messagingSenderId: '201460195049',
    projectId: 'recipe-app-39a72',
    storageBucket: 'recipe-app-39a72.firebasestorage.app',
    iosBundleId: 'com.example.cocktailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvztd0ASYHtelJc7P8FzZhcWgypH_hCOk',
    appId: '1:201460195049:ios:903263870401e0e28c1a78',
    messagingSenderId: '201460195049',
    projectId: 'recipe-app-39a72',
    storageBucket: 'recipe-app-39a72.firebasestorage.app',
    iosBundleId: 'com.example.cocktailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE83jbFQcMsuuqmcqhglqJcwD5SrvQUuc',
    appId: '1:201460195049:web:3f8f75408627c9da8c1a78',
    messagingSenderId: '201460195049',
    projectId: 'recipe-app-39a72',
    authDomain: 'recipe-app-39a72.firebaseapp.com',
    storageBucket: 'recipe-app-39a72.firebasestorage.app',
    measurementId: 'G-4EFLET2R9G',
  );
}
