name: Flutter CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - Attempt-to-impliment-Firestorage
  pull_request:
    branches:
      - main
      - Attempt-to-impliment-Firestorage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"

      - name: Install Dependencies
        run: flutter pub get

      # - name: Run Tests
      #   run: flutter test

      - name: Build APK
        run: flutter build apk --release
